name: trace_or
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  go_router: ^14.3.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  toastification: ^2.3.0
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.3.2
  flutter_localization: ^0.2.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  image_path: 'assets/checklist.png'
  android: true

flutter:
  uses-material-design: true
  assets: 
    - assets/logo.png
    - assets/medical-college-logo.svg
    - assets/checklist.svg
